"""
Created by: Taylor Denouden
Organization: Hakai Institute
Date: 2020-09-17
Description: 
"""

# String constants reduce occurrence of silent errors due to typos when doing comparisons
BLUE = "BLUE"
GREEN = "GREEN"
RED = "RED"
REDEDGE = "REDEDGE"
NIR = "NIR"

METHOD_THRESHOLD = "METHOD_THRESHOLD"
METHOD_RATIO = "METHOD_RATIO"

IMG_TYPE_RGB = "IMG_TYPE_RGB"
IMG_TYPE_ACO = "IMG_TYPE_ACO"
IMG_TYPE_P4MS = "IMG_TYPE_P4MS"
IMG_TYPE_MICASENSE_REDEDGE = "IMG_TYPE_MICASENSE_REDEDGE"

# Default slider values in GUI
DEFAULT_BLUE_THRESH = 0.875
DEFAULT_GREEN_THRESH = 1.000
DEFAULT_RED_THRESH = 1.000
DEFAULT_REDEDGE_THRESH = 1.000
DEFAULT_NIR_THRESH = 1.000
DEFAULT_PIXEL_BUFFER = 0
DEFAULT_MAX_WORKERS = 0
