name: Build GUI

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - '*.*.*'
      - '*.*.*rc*'
      - 'v*.*.*'
      - 'v*.*.*rc*'
jobs:

  Linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        id: tag
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pyinstaller
          pip install -r requirements.txt
      - name: Building GUI
        run: |
          pyinstaller --name=GlintMaskGenerator-${{ steps.tag.outputs.tag }} -F --windowed --icon=resources/gmt.ico gui.py
      - name: Building CLI
        run: |
          pyinstaller --name=glint-mask-${{ steps.tag.outputs.tag }} -F cli.py
      - name: Gzip release
        run: |
          tar -czvf dist/GlintMaskGenerator-${{ steps.tag.outputs.tag }}-linux.tar.gz -C dist GlintMaskGenerator-${{ steps.tag.outputs.tag }} glint-mask-${{ steps.tag.outputs.tag }}
      - name: Upload Gzip artifact
        uses: actions/upload-artifact@v1
        with:
          name: GlintMaskGenerator-${{ steps.tag.outputs.tag }}-linux.tar.gz
          path: dist/GlintMaskGenerator-${{ steps.tag.outputs.tag }}-linux.tar.gz

  Windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        id: tag
        shell: bash
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pyinstaller
          pip install -r requirements.txt
      - name: Building GUI
        run: |
          pyinstaller --name=GlintMaskGenerator-${{ steps.tag.outputs.tag }} -F --windowed --icon=resources/gmt.ico gui.py
      - name: Building CLI
        run: |
          pyinstaller --name=glint-mask-${{ steps.tag.outputs.tag }} -F cli.py
      - name: Zip release
        run: |
          cd dist
          7z a GlintMaskGenerator-${{ steps.tag.outputs.tag }}-win64.zip GlintMaskGenerator-${{ steps.tag.outputs.tag }}.exe glint-mask-${{ steps.tag.outputs.tag }}.exe
          cd -
      - name: Upload Zip artifact
        uses: actions/upload-artifact@v1
        with:
          name: GlintMaskGenerator-${{ steps.tag.outputs.tag }}-win64.zip
          path: dist/GlintMaskGenerator-${{ steps.tag.outputs.tag }}-win64.zip

  Release:
    needs: [Linux, Windows]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Detect prerelease
        id: prerelease
        run: |
          if echo ${{ steps.tag.outputs.tag }} | grep -qe '?*.*.*rc*'; then
              echo ::set-output name=prerelease::true
          else
              echo ::set-output name=prerelease::false
          fi
      - name: Download Linux gzip release file
        uses: actions/download-artifact@master
        with:
          name: GlintMaskGenerator-${{ steps.tag.outputs.tag }}-linux.tar.gz
          path: dist/GlintMaskGenerator-${{ steps.tag.outputs.tag }}-linux.tar.gz
      - name: Download Windows zip release file
        uses: actions/download-artifact@master
        with:
          name: GlintMaskGenerator-${{ steps.tag.outputs.tag }}-win64.zip
          path: dist/GlintMaskGenerator-${{ steps.tag.outputs.tag }}-win64.zip
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: ${{ steps.prerelease.outputs.prerelease }}
      - name: Upload Linux gzip release file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/GlintMaskGenerator-${{ steps.tag.outputs.tag }}-linux.tar.gz/GlintMaskGenerator-${{ steps.tag.outputs.tag }}-linux.tar.gz
          asset_name: GlintMaskGenerator-${{ steps.tag.outputs.tag }}-linux.tar.gz
          asset_content_type: application/gzip
      - name: Upload Windows zip release file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/GlintMaskGenerator-${{ steps.tag.outputs.tag }}-win64.zip/GlintMaskGenerator-${{ steps.tag.outputs.tag }}-win64.zip
          asset_name: GlintMaskGenerator-${{ steps.tag.outputs.tag }}-win64.zip
          asset_content_type: application/zip